# Generated by Django 5.0.4 on 2024-04-16 11:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_remove_event_create_time_alter_event_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='Notebook',
        ),
        migrations.RenameField(
            model_name='notebook',
            old_name='date',
            new_name='create_date',
        ),
    ]
