# Generated by Django 5.0.4 on 2024-04-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0006_rename_report_notebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
